---
- name: Install docker package
  hosts: all
  become: true
  become_method: ansible.builtin.sudo

  tasks:
    - name: Install docker
      ansible.builtin.apt:
        name: docker.io
        state: present
